// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dgashaw11/go-ms-universe/internal/product (interfaces: EventPublisher)
//
// Generated by this command:
//
//	mockgen -destination=mock/event_publisher_mock.go -package=mock . EventPublisher
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	product "github.com/dgashaw11/go-ms-universe/internal/product"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// ProductCreated mocks base method.
func (m *MockEventPublisher) ProductCreated(ctx context.Context, p product.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProductCreated", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProductCreated indicates an expected call of ProductCreated.
func (mr *MockEventPublisherMockRecorder) ProductCreated(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProductCreated", reflect.TypeOf((*MockEventPublisher)(nil).ProductCreated), ctx, p)
}

// ProductDeleted mocks base method.
func (m *MockEventPublisher) ProductDeleted(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProductDeleted", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProductDeleted indicates an expected call of ProductDeleted.
func (mr *MockEventPublisherMockRecorder) ProductDeleted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProductDeleted", reflect.TypeOf((*MockEventPublisher)(nil).ProductDeleted), ctx, id)
}
